### ISSUE TITLE
No such file or directory: '/config/www/alexa_tts'

### ISSUE THREAD

**Issue by Dustinhoefer** [custom-components/alexa_media_player#2022]
**Describe the bug**

After following some tutorials, I still can't get the service to find my devices.
The login works, but after that, no devices are found.

**To Reproduce**

Follow this tutorial:
https://www.youtube.com/watch?v=UEPt3edhwc0

**Expected behavior**

Devices are listed

**Screenshots**

**System details**

- Home-assistant (version): 2023.09.2
- alexa_media (version from `const.py` or HA startup): 
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/media_player.py", line 157, in async_setup_entry
    if await async_setup_platform(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/media_player.py", line 105, in async_setup_platform
    os.mkdir(UPLOAD_PATH)
FileNotFoundError: [Errno 2] No such file or directory: '/config/www/alexa_tts'

**Additional context**

**Comment by Dustinhoefer** [comment]
I fixed this, by just creating the requested folder structure manually...

**Comment by jsight** [comment]
I have updated and rebooted and I still see the same error:
```FileNotFoundError: [Errno 2] No such file or directory: '/config/www/alexa_tts'
```

I am on 4.7.1
