### ISSUE TITLE
last_alexa sensor stops working after upgrade to 2.7.1 and 2.7.2

### ISSUE THREAD

**Issue by timota** [custom-components/alexa_media_player#712]
**Describe the bug**
last_alexa sensor stops working after upgrade to 2.7.1 and 2.7.2

**Expected behavior**
Sensors should be updated with last called alexa

**System details**
 - Home-assistant (version): 0.109.6
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): _version__ = "2.7.2
 - alexapy (version from `pip show alexapy` or HA startup): alexapy==1.8.4

**Logs**

1. Call alexa broadcast
2. check last_alexa sensor

```
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Message: My test message, kwargs: {'target': ['media_player.echo_dot'], 'data': {'type': 'announce'}}
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: media_player.echo_dot against (<Entity tata: standby>, tata, G************DMR, media_player.tata)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: media_player.echo_dot against (<Entity Echo Dot: standby>, Echo Dot, G************4R4, media_player.echo_dot)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Converting: media_player.echo_dot to (entities): <Entity Echo Dot: standby>
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: media_player.echo_dot against (<Entity Tetiana: standby>, Tetiana, G************HV8, media_player.tetiana)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: media_player.echo_dot against (<Entity Taras's Sonos One: standby>, Taras's Sonos One, 2****************************a37, media_player.taras_s_sonos_one)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: media_player.echo_dot against (<Entity Office: standby>, Office, 9****************************32e, media_player.office)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: media_player.echo_dot against (<Entity Office 2: standby>, Office 2, 5****************************570, media_player.office_2)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: media_player.echo_dot against (<Entity This Device: standby>, This Device, 1****************************865, media_player.this_device)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity tata: standby>, tata, G************DMR, media_player.tata)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Echo Dot: standby>, Echo Dot, G************4R4, media_player.echo_dot)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Converting: <Entity Echo Dot: standby> to (serialnumbers): G090LF10729614R4
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Tetiana: standby>, Tetiana, G************HV8, media_player.tetiana)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Taras's Sonos One: standby>, Taras's Sonos One, 2****************************a37, media_player.taras_s_sonos_one)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Office: standby>, Office, 9****************************32e, media_player.office)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Office 2: standby>, Office 2, 5****************************570, media_player.office_2)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity This Device: standby>, This Device, 1****************************865, media_player.this_device)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Announce targets: ['G************4R4'] entities: [<Entity Echo Dot: standby>]
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity tata: standby>, tata, G************DMR, media_player.tata)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Echo Dot: standby>, Echo Dot, G************4R4, media_player.echo_dot)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Converting: <Entity Echo Dot: standby> to (serialnumbers): G090LF10729614R4
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Tetiana: standby>, Tetiana, G************HV8, media_player.tetiana)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Taras's Sonos One: standby>, Taras's Sonos One, 2****************************a37, media_player.taras_s_sonos_one)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Office: standby>, Office, 9****************************32e, media_player.office)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity Office 2: standby>, Office 2, 5****************************570, media_player.office_2)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot: standby> against (<Entity This Device: standby>, This Device, 1****************************865, media_player.this_device)
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] Announce targets: ['G************4R4'] entities: [<Entity Echo Dot: standby>]
2020-05-12 16:17:13 DEBUG (MainThread) [custom_components.alexa_media.notify] t**********o@g*******m: Announce by <Entity Echo Dot: standby> to targets: ['G************4R4']: My test message
2020-05-12 16:17:14 DEBUG (MainThread) [alexapy.alexaapi] Creating sequence for 1 items
2020-05-12 16:17:14 DEBUG (MainThread) [alexapy.alexaapi] Running behavior with data: {"behaviorId": "PREVIEW", "sequenceJson": "{\"@type\": \"com.amazon.alexa.behaviors.model.Sequence\", \"startNode\": {\"@type\": \"com.amazon.alexa.behaviors.model.SerialNode\", \"nodesToExecute\": [{\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"AlexaAnnouncement\", \"operationPayload\": {\"deviceType\": \"A3S5BH2HU6VAYF\", \"deviceSerialNumber\": \"G090LF10729614R4\", \"locale\": \"en-gb\", \"customerId\": \"A2JC2JHY2355FU\", \"expireAfter\": \"PT5S\", \"content\": [{\"locale\": \"en-gb\", \"display\": {\"title\": \"Home Assistant\", \"body\": \"My test message\"}, \"speak\": {\"type\": \"text\", \"value\": \"My test message\"}}], \"target\": {\"customerId\": \"A2JC2JHY2355FU\", \"devices\": [{\"deviceSerialNumber\": \"G090LF10729614R4\", \"deviceTypeId\": \"A3S5BH2HU6VAYF\"}]}, \"skillId\": \"amzn1.ask.1p.routines.messaging\"}}]}}", "status": "ENABLED"}
2020-05-12 16:17:15 DEBUG (MainThread) [alexapy.alexaapi] POST: https://alexa.amazon.co.uk/api/behaviors/preview returned 200:OK:application/octet-stream
2020-05-12 16:17:16 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x0e994fe7 f 0x00000001 0xeeb7a69e 0x0000022e GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:A2JC2JHY2355FU:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:260-9248940-0895229-1589296547000 {"payload":"{\"destinationUserId\":\"A2JC2JHY2355FU\",\"dopplerId\":{\"deviceType\":\"A3S5BH2HU6VAYF\",\"deviceSerialNumber\":\"G090LF10729614R4\"},\"bass\":0,\"midrange\":0,\"treble\":0}","command":"PUSH_EQUALIZER_STATE_CHANGE"}FABE
2020-05-12 16:17:16 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media] t**********o@g*******m: Received websocket command: PUSH_EQUALIZER_STATE_CHANGE : {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'bass': 0, 'midrange': 0, 'treble': 0}
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media] Adding PUSH_EQUALIZER_STATE_CHANGE to seen_commands: {'PUSH_EQUALIZER_STATE_CHANGE': 1589296636.081319}
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player availability {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'bass': 0, 'midrange': 0, 'treble': 0}
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media.media_player] t**********o@g*******m: No PUSH_AUDIO_PLAYER_STATE/PUSH_MEDIA_CHANGE/PUSH_MEDIA_PROGRESS_CHANGE in dict_keys(['PUSH_EQUALIZER_STATE_CHANGE']);forcing refresh
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media.media_player] t**********o@g*******m: Refreshing Echo Dot
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media.media_player] Echo Dot: Last_called check: self: G************4R4 reported: G************HV8
2020-05-12 16:17:16 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x0e7c4a45 f 0x00000001 0x9c9e77a4 0x00000225 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:A2JC2JHY2355FU:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:260-9248940-0895229-1589296547000 {"payload":"{\"destinationUserId\":\"A2JC2JHY2355FU\",\"dopplerId\":{\"deviceType\":\"A3S5BH2HU6VAYF\",\"deviceSerialNumber\":\"G090LF10729614R4\"},\"volumeSetting\":83,\"isMuted\":false}","command":"PUSH_VOLUME_CHANGE"}FABE
2020-05-12 16:17:16 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media] t**********o@g*******m: Received websocket command: PUSH_VOLUME_CHANGE : {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'volumeSetting': 83, 'isMuted': False}
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media] Adding PUSH_VOLUME_CHANGE to seen_commands: {'PUSH_EQUALIZER_STATE_CHANGE': 1589296636.081319, 'PUSH_VOLUME_CHANGE': 1589296636.0869043}
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player volume: {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'volumeSetting': 83, 'isMuted': False}
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media.media_player] Echo Dot volume updated: 83
2020-05-12 16:17:16 DEBUG (MainThread) [custom_components.alexa_media.media_player] t**********o@g*******m: No PUSH_AUDIO_PLAYER_STATE/PUSH_MEDIA_CHANGE/PUSH_MEDIA_PROGRESS_CHANGE in dict_keys(['PUSH_EQUALIZER_STATE_CHANGE', 'PUSH_VOLUME_CHANGE']);forcing refresh
2020-05-12 16:17:16 DEBUG (MainThread) [alexapy.alexaapi] GET: https://alexa.amazon.co.uk/api/np/player?deviceSerialNumber=G090LF10729614R4&deviceType=A3S5BH2HU6VAYF&screenWidth=2560 returned 200:OK:application/json
2020-05-12 16:17:19 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x0e638095 f 0x00000001 0xe6bb706f 0x0000022e GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:A2JC2JHY2355FU:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:260-9248940-0895229-1589296547000 {"payload":"{\"destinationUserId\":\"A2JC2JHY2355FU\",\"dopplerId\":{\"deviceType\":\"A3S5BH2HU6VAYF\",\"deviceSerialNumber\":\"G090LF10729614R4\"},\"bass\":0,\"midrange\":0,\"treble\":0}","command":"PUSH_EQUALIZER_STATE_CHANGE"}FABE
2020-05-12 16:17:19 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media] t**********o@g*******m: Received websocket command: PUSH_EQUALIZER_STATE_CHANGE : {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'bass': 0, 'midrange': 0, 'treble': 0}
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player availability {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'bass': 0, 'midrange': 0, 'treble': 0}
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media.media_player] t**********o@g*******m: No PUSH_AUDIO_PLAYER_STATE/PUSH_MEDIA_CHANGE/PUSH_MEDIA_PROGRESS_CHANGE in dict_keys(['PUSH_EQUALIZER_STATE_CHANGE', 'PUSH_VOLUME_CHANGE']);forcing refresh
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media.media_player] t**********o@g*******m: Refreshing Echo Dot
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media.media_player] Echo Dot: Last_called check: self: G************4R4 reported: G************HV8
2020-05-12 16:17:19 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x0e83a5c4 f 0x00000001 0x6bcb4bd4 0x00000225 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:A2JC2JHY2355FU:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:260-9248940-0895229-1589296547000 {"payload":"{\"destinationUserId\":\"A2JC2JHY2355FU\",\"dopplerId\":{\"deviceType\":\"A3S5BH2HU6VAYF\",\"deviceSerialNumber\":\"G090LF10729614R4\"},\"volumeSetting\":83,\"isMuted\":false}","command":"PUSH_VOLUME_CHANGE"}FABE
2020-05-12 16:17:19 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media] t**********o@g*******m: Received websocket command: PUSH_VOLUME_CHANGE : {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'volumeSetting': 83, 'isMuted': False}
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player volume: {'destinationUserId': 'A**********5FU', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************4R4'}, 'volumeSetting': 83, 'isMuted': False}
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media.media_player] Echo Dot volume updated: 83
2020-05-12 16:17:19 DEBUG (MainThread) [custom_components.alexa_media.media_player] t**********o@g*******m: No PUSH_AUDIO_PLAYER_STATE/PUSH_MEDIA_CHANGE/PUSH_MEDIA_PROGRESS_CHANGE in dict_keys(['PUSH_EQUALIZER_STATE_CHANGE', 'PUSH_VOLUME_CHANGE']);forcing refresh
2020-05-12 16:17:19 DEBUG (MainThread) [alexapy.alexaapi] GET: https://alexa.amazon.co.uk/api/np/player?deviceSerialNumber=G090LF10729614R4&deviceType=A3S5BH2HU6VAYF&screenWidth=2560 returned 200:OK:application/json

```

**Additional context**
last_alexa sensor configuration:

```
sensor:
  - platform: template
    sensors: 
      last_alexa: 
        entity_id: 
          - media_player.<alexa1>
          - media_player.<alexa2>
          - media_player.echo_dot
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}

```

**Comment by timota** [comment]
media_player state after it has been called:

```
source_list:
  - Local Speaker
volume_level: 0.83
is_volume_muted: false
media_content_type: standby
media_position_updated_at: '2020-05-12T15:17:19.968652+00:00'
source: Local Speaker
available: true
last_called: false
last_called_timestamp: null
friendly_name: Echo Dot
supported_features: 56253
```

other media_player that has been called long time ago:
```
volume_level: 0.2
is_volume_muted: false
media_content_type: standby
media_position_updated_at: '2020-05-12T15:21:40.110404+00:00'
available: true
last_called: true
last_called_timestamp: 1589265066456
friendly_name: Tetiana
supported_features: 56253
```

as for me - integration did not updated or updated `last_called:` attribute for a wrong device

**Comment by timota** [comment]
after downgrading to 2.6.1 - same issue. Thats strange

**Comment by alandtse** [comment]
Try renaming your .pickle file. It's in /config/.storage. It sounds like your login has expired if it's persisting down at 2.6.1.

**Comment by alandtse** [comment]
Also, definitely get off 2.7.1 or 2.7.2. There's a nasty bug on reboot fixed in 2.7.3.

**Comment by timota** [comment]
2.7.3 fixed issue with reboot. But issue with sensor still persists.

**Comment by timota** [comment]
Downgraded to 2.6.1 - same issue. Strange thing, just called alexa(Tetiana)

```
volume_level: 0.2
is_volume_muted: false
media_content_type: standby
media_position_updated_at: '2020-05-12T17:33:48.374285+00:00'
available: true
last_called: true
last_called_timestamp: 1589265066456
friendly_name: Tetiana
supported_features: 56253
```

as for me timestamp has to be updated - but it the same as was couple hours ago. (check second comment on this thread). Now im lost - is it related to HASS itself somehow or Integration.

**Comment by timota** [comment]
Looks like i found why sensor has not been updated. If im using 
```
data:
  type: tts
```
sensor has been updated

if 
```
data:
  type: announce
```
it doesnt updated. 

Anyway - sensor works with version 2.7.3. Issue can be closed and sorry.
